### PR TITLE
Did some cleanup to conform to latest CI style.

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by jchodera** [comment]
Looks good!  3.3 is failing, but why not add 3.4 as well?

**Comment by kyleabeauchamp** [comment]
I think this is good now.  The Travis tests die early due to timeout, but things seem fine on my machine.

**Comment by jchodera** [comment]
All we need to do to avoid timeout is to ensure output is generated more frequently than every 10 min.  Let me look at that test...

**Comment by jchodera** [comment]
Can you just reduce the number of iterations here by a factor of 10?
https://github.com/choderalab/repex/blob/master/tests-nose/test_hamiltonian_exchange_dummy_mpi.py#L68-L75

**Comment by kyleabeauchamp** [comment]
We should make a separate pr

**Pull request merged**
